// Authenticated quotes from Imam Ali (A.S)
// Sources: Nahj al-Balagha and Ghurar al-Hikam

export const quotes = [
  {
    id: 1,
    arabic: "العلم خير من المال",
    english: "Knowledge is better than wealth",
    urdu: "علم مال سے بہتر ہے",
    source: "Nahj al-Balagha, Saying 147",
    category: "knowledge",
    authenticity: "high",
  },
  {
    id: 2,
    arabic: "الصبر من الإيمان بمنزلة الرأس من الجسد",
    english: "Patience is to faith as the head is to the body",
    urdu: "صبر ایمان میں ایسا ہے جیسے سر جسم میں",
    source: "Nahj al-Balagha, Saying 82",
    category: "patience",
    authenticity: "high",
  },
  {
    id: 3,
    arabic: "من كساه الحياء ثوبه لم ير الناس عيبه",
    english: "He who is clothed with modesty, people will not see his faults",
    urdu: "جس نے حیا کا لباس پہنا لوگ اس کے عیب نہیں دیکھیں گے",
    source: "Ghurar al-Hikam, 8581",
    category: "modesty",
    authenticity: "high",
  },
  {
    id: 4,
    arabic: "قيمة كل امرئ ما يحسنه",
    english: "The worth of every person is in what they are good at",
    urdu: "ہر شخص کی قیمت اس میں ہے جس میں وہ ماہر ہو",
    source: "Nahj al-Balagha, Saying 81",
    category: "wisdom",
    authenticity: "high",
  },
  {
    id: 5,
    arabic: "العقل حفظ التجارب",
    english: "Wisdom is preservation of experiences",
    urdu: "عقل تجربات کی حفاظت ہے",
    source: "Nahj al-Balagha, Saying 1",
    category: "wisdom",
    authenticity: "high",
  },
  {
    id: 6,
    arabic: "من نصب نفسه للناس إماماً فليبدأ بتعليم نفسه قبل تعليم غيره",
    english:
      "Whoever sets himself up as a leader for people should start by teaching himself before teaching others",
    urdu: "جو شخص لوگوں کا امام بننا چاہے اسے پہلے خود کو سکھانا چاہیے دوسروں کو سکھانے سے پہلے",
    source: "Nahj al-Balagha, Saying 73",
    category: "leadership",
    authenticity: "high",
  },
  {
    id: 7,
    arabic: "أشد الذنوب ما استخف به صاحبه",
    english: "The worst sin is that which the sinner considers trivial",
    urdu: "سب سے بڑا گناہ وہ ہے جسے گناہ گار معمولی سمجھے",
    source: "Nahj al-Balagha, Saying 477",
    category: "sin",
    authenticity: "high",
  },
  {
    id: 8,
    arabic: "الحكمة ضالة المؤمن",
    english: "Wisdom is the lost property of the believer",
    urdu: "حکمت مومن کی کھوئی ہوئی چیز ہے",
    source: "Ghurar al-Hikam, 1929",
    category: "wisdom",
    authenticity: "high",
  },
  {
    id: 9,
    arabic: "لا تستح من إعطاء القليل فإن الحرمان أقل منه",
    english: "Do not be ashamed of giving little, for deprivation is even less",
    urdu: "تھوڑا دینے سے شرمندہ نہ ہو کیونکہ محرومی اس سے بھی کم ہے",
    source: "Nahj al-Balagha, Saying 370",
    category: "charity",
    authenticity: "high",
  },
  {
    id: 10,
    arabic: "الصدقة دواء منجح",
    english: "Charity is an effective cure",
    urdu: "صدقہ ایک کارگر علاج ہے",
    source: "Nahj al-Balagha, Saying 146",
    category: "charity",
    authenticity: "high",
  },
];
